### ISSUE TITLE
up2b命令报错

### ISSUE THREAD

**Issue by LOStacNet** [thep0y/up2b#6]
pip 安装后，使用up2b命令报错，信息如下：
`PS C:\Users\HU\Desktop> up2b
Traceback (most recent call last):
  File "c:\users\hu\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hu\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HU\AppData\Local\Programs\Python\Python39\Scripts\up2b.exe\__main__.py", line 4, in <module>
  File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\__init__.py", line 19, in <module>
    from up2b.up2b_lib.i18n import read_i18n
  File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\up2b_lib\i18n.py", line 15, in <module>
    from up2b.up2b_lib.utils import get_default_language
  File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\up2b_lib\utils.py", line 31, in <module>
    from up2b.up2b_lib.log import child_logger
  File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\up2b_lib\log.py", line 9, in <module>
    from colorful_logger import get_logger, child_logger as cl
  File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\colorful_logger\__init__.py", line 9, in <module>
    from colorful_logger.logger import (
  File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\colorful_logger\logger.py", line 16, in <module>
    from colorful_logger.types import StrPath
  File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\colorful_logger\types.py", line 11, in <module>
    StrPath = str | PathLike[str]
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'`

**Comment by thep0y** [comment]
明天发布修复版发自我的 iPhone在 2023年2月20日，22:46，LO_StacNet ***@***.***> 写道：﻿
pip 安装后，使用up2b命令报错，信息如下：
PS C:\Users\HU\Desktop> up2b Traceback (most recent call last): File "c:\users\hu\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\users\hu\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\HU\AppData\Local\Programs\Python\Python39\Scripts\up2b.exe\__main__.py", line 4, in <module> File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\__init__.py", line 19, in <module> from up2b.up2b_lib.i18n import read_i18n File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\up2b_lib\i18n.py", line 15, in <module> from up2b.up2b_lib.utils import get_default_language File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\up2b_lib\utils.py", line 31, in <module> from up2b.up2b_lib.log import child_logger File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\up2b\up2b_lib\log.py", line 9, in <module> from colorful_logger import get_logger, child_logger as cl File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\colorful_logger\__init__.py", line 9, in <module> from colorful_logger.logger import ( File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\colorful_logger\logger.py", line 16, in <module> from colorful_logger.types import StrPath File "c:\users\hu\appdata\local\programs\python\python39\lib\site-packages\colorful_logger\types.py", line 11, in <module> StrPath = str | PathLike[str] TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'

**Comment by thep0y** [comment]
```bash
pip install -U up2b -i https://pypi.org/simple
```

如果修复了这个 bug 请关闭此 issue。
