### ISSUE TITLE
大佬，是不是最近更新了，上传图片报错

### ISSUE THREAD

**Issue by longhuishen** [thep0y/up2b#9]
def upload(save_path):
    save_path = save_path
    im = Imgtu()
    print("正在上传图片...")
    res = im.upload_image(img/img.jpg)
    if isinstance(res, str):
        return res
    else:
        logger.fatal("上传出错：%s", res)

Traceback (most recent call last):
  File "/ql/data/scripts/mryxh_zj.py", line 140, in <module>
    main()
  File "/ql/data/scripts/mryxh_zj.py", line 134, in main
    imgurl = upload1(neirong_list[1])
  File "/ql/data/scripts/mryxh_zj.py", line 58, in upload1
    res = im.upload_image(save_path)
  File "/usr/local/lib/python3.10/site-packages/up2b/up2b_lib/up2b_api/imgtu.py", line 241, in upload_image
    return self.__upload(image_path)
  File "/usr/local/lib/python3.10/site-packages/up2b/up2b_lib/up2b_api/imgtu.py", line 145, in __upload
    url, md5, ok = self._check_cache(image)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/up2b/up2b_lib/up2b_api/__init__.py", line 309, in _check_cache
    url, md5, ok = self.cache.check_cache_of_image_bed(
  File "/usr/local/lib/python3.10/site-packages/up2b/up2b_lib/cache.py", line 105, in check_cache_of_image_bed
    md5 = file_md5(filepath)
  File "/usr/local/lib/python3.10/site-packages/up2b/up2b_lib/cache.py", line 34, in file_md5
    with filepath.open("rb") as f:
AttributeError: 'str' object has no attribute 'open'

**Comment by thep0y** [comment]
`upload_image`的参数类型是`pathlib.Path`，不是`str`，改成：
```python
from pathlib import Path

im = Imgtu()

image_path = Path("/path/to/image")
if not image_path.exists():
    logger.fatal('图片不存在，请检查路径')

res = im.upload_image(image_path)

# ...
```

另外 python 包不会自动更新，我上传了新版本不会改变你正常使用的本地版本，虽然我建议能升级就升级。

```bash
pip install up2b --upgrade
```

**Comment by longhuishen** [comment]
> `upload_image`的参数类型是`pathlib.Path`，不是`str`，改成：
> ```python
> from pathlib import Path
> 
> im = Imgtu()
> 
> image_path = Path("/path/to/image")
> if not image_path.exists():
>     logger.fatal('图片不存在，请检查路径')
> 
> res = im.upload_image(image_path)
> 
> # ...
> ```
> 
> 另外 python 包不会自动更新，我上传了新版本不会改变你正常使用的本地版本，虽然我建议能升级就升级。
> 
> ```bash
> pip install up2b --upgrade
> ```

好的  感谢哈  我更新了下发现用不了了

**Comment by thep0y** [comment]
新版已经alpha了好几个版本了，一直没 release。
